import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import "bootstrap/dist/css/bootstrap.min.css";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: session, status } = useSession();

  if (session) {
    const userName = session!.user!.name!;

    return (
      <div className={styles.container}>
        <Head>
          <title>Jira Clone</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h1 className={styles.title}>
            Welcome, <span>{userName.substring(0, userName.indexOf(" "))}</span>{" "}
            to <p className="font-weight-bold text-primary">Jira Clone</p>
          </h1>

          <div className={styles.grid}>
            <Link href="/board">
              <a className={styles.card}>
                <h2>Scrum Board &rarr;</h2>
                <p>
                  The Jira scrum board is the tool that unites teams around a
                  single goal.
                </p>
              </a>
            </Link>

            <Link href="/about">
              <a className={styles.card}>
                <h2>About &rarr;</h2>
                <p>Learn more about the developer team behind Jira Clone</p>
              </a>
            </Link>
          </div>
        </main>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Jira Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <p className="font-weight-bold text-primary">Jira Clone</p>
        </h1>

        <div className={styles.grid}>
          <Link href="/login">
            <a className={styles.card}>
              <h2>Sign In &rarr;</h2>
              <p>Sign In to see your tasks on your board.</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
